/* Generated by Copilot Core. */

#include <stdint.h>
#include <stdbool.h>

/* Observers (defined by Copilot): */


/* Triggers (must be defined by user): */

void shiftOut(uint32_t);

/* External variables (must be defined by user): */


/* External arrays (must be defined by user): */


/* External functions (must be defined by user): */


/* Step function: */

void step();